name: 'AWS cli install action'
description: 'Installs AWS CLI'
author: 'chrislennon'
branding:
  icon: 'terminal'
  color: 'gray-dark'
runs:
  pre: chainguard-phonehome.js
  using: 'node12'
  main: 'lib/main.js'
